insert into employee (id, first_name, last_name, email) values (1,'Rick','Stewart', 'rick.stewart@dlt.com');
insert into employee (id, first_name, last_name, email) values (2,'Matt','Micene', 'matt.micene@dlt.com');
insert into employee (id, first_name, last_name, email) values (3,'Jason','Quinn', 'jason.quinn@dlt.com');
insert into employee (id, first_name, last_name, email) values (4,'Jake','Wasser', 'jake.wasser@dlt.com');
insert into employee (id, first_name, last_name, email) values (5,'Tyler','Price', 'tyler.price@dlt.com');
insert into employee (id, first_name, last_name, email) values (6,'Jonathan','Bowe', 'jonathan.bowe@dlt.com');
insert into employee (id, first_name, last_name, email) values (7,'Jennifer','Triplett', 'jennifer.triplett@dlt.com');
insert into employee (id, first_name, last_name, email) values (8,'Klint','Simpson', 'klint.simpson@dlt.com');
insert into employee (id, first_name, last_name, email) values (9,'Joe','Perrino', 'joe.perrino@dlt.com');
insert into employee (id, first_name, last_name, email) values (10,'Jim','Propps', 'jim.propps@dlt.com');
insert into employee (id, first_name, last_name, email) values (11,'Jason','Schmidt', 'jason.schmidt@dlt.com');
insert into employee (id, first_name, last_name, email) values (12,'Kyle','Petrosino', 'kyle.petrosino@dlt.com');
insert into employee (id, first_name, last_name, email) values (13,'Dana','Suarez', 'dana.suarez@dlt.com');
insert into employee (id, first_name, last_name, email) values (14,'Erica','Gallagher', 'erica.gallagher@dlt.com');
insert into employee (id, first_name, last_name, email) values (15,'Jason','Erickson', 'jason.erickson@dlt.com');
insert into employee (id, first_name, last_name, email) values (16,'Kevin','Corey', 'kevin.corey@dlt.com');
insert into employee (id, first_name, last_name, email) values (17,'Samantha','Hartle', 'samantha.hartle@dlt.com');
insert into employee (id, first_name, last_name, email) values (18,'Justin','Robinson', 'justin.robinson@dlt.com');
insert into employee (id, first_name, last_name, email) values (19,'Michelle','Meadows', 'michelle.meadows@dlt.com');
insert into employee (id, first_name, last_name, email) values (20,'Kevin','Pence', 'kevin.pence@dlt.com');
insert into employee (id, first_name, last_name, email) values (21,'Sam','Biesenbach', 'sam.biesenbach@dlt.com');
insert into employee (id, first_name, last_name, email) values (22,'Chad','Austin', 'chad.austin@dlt.com');
insert into employee (id, first_name, last_name, email) values (23,'James','Kovach', 'james.kovach@dlt.com');
insert into employee (id, first_name, last_name, email) values (24,'David','Tootle', 'david.tootle@dlt.com');
insert into employee (id, first_name, last_name, email) values (25,'Amanda','Truong', 'amanda.truong@dlt.com');
insert into employee (id, first_name, last_name, email) values (26,'Matt','Ludeman', 'matt.ludeman@dlt.com');
insert into employee (id, first_name, last_name, email) values (27,'Lakeisha','Thomas', 'lakeisha.thomas@dlt.com');

insert into provider (id, name, website_url) values (1, 'Bagel Cafe', 'http://www.bagelcafe.com/');
insert into provider (id, name, website_url) values (2, 'Anitas', 'http://www.anitascorp.com/');

-- DLT EP Breakfast Schedule
insert into schedule (id, emp_id, delivery_date) values (2,21,'2016-01-22');
insert into schedule (id, emp_id, delivery_date) values (3,20,'2016-01-29');
insert into schedule (id, emp_id, delivery_date) values (4,22,'2016-02-05');
insert into schedule (id, emp_id, delivery_date) values (5,23,'2016-02-12');
insert into schedule (id, emp_id, delivery_date) values (6,11,'2016-02-19');
insert into schedule (id, emp_id, delivery_date) values (7,8,'2016-02-26');
insert into schedule (id, emp_id, delivery_date) values (8,4,'2016-03-04');
insert into schedule (id, emp_id, delivery_date) values (9,12,'2016-03-11');
insert into schedule (id, emp_id, delivery_date) values (10,15,'2016-03-18');
insert into schedule (id, emp_id, delivery_date) values (11,7,'2016-03-25');
insert into schedule (id, emp_id, delivery_date) values (12,3,'2016-04-01');
insert into schedule (id, emp_id, delivery_date) values (13,20,'2016-04-08');
insert into schedule (id, emp_id, delivery_date) values (14,2,'2016-04-15');
insert into schedule (id, emp_id, delivery_date) values (15,17,'2016-04-22');
insert into schedule (id, emp_id, delivery_date) values (16,1,'2016-04-29');
insert into schedule (id, emp_id, delivery_date) values (17,6,'2016-05-06');
insert into schedule (id, emp_id, delivery_date) values (18,13,'2016-05-13');
insert into schedule (id, emp_id, delivery_date) values (19,10,'2016-05-20');
insert into schedule (id, emp_id, delivery_date) values (20,18,'2016-05-26');
insert into schedule (id, emp_id, delivery_date) values (21,4,'2016-06-03');
insert into schedule (id, emp_id, delivery_date) values (22,16,'2016-06-10');
insert into schedule (id, emp_id, delivery_date) values (23,21,'2016-06-17');
insert into schedule (id, emp_id, delivery_date) values (24,9,'2016-06-24');
insert into schedule (id, emp_id, delivery_date) values (25,22,'2016-07-01');
insert into schedule (id, emp_id, delivery_date) values (26,3,'2016-07-08');
insert into schedule (id, emp_id, delivery_date) values (27,11,'2016-07-15');
insert into schedule (id, emp_id, delivery_date) values (28,5,'2016-07-22');
insert into schedule (id, emp_id, delivery_date) values (29,12,'2016-07-29');
insert into schedule (id, emp_id, delivery_date) values (30,15,'2016-08-05');
insert into schedule (id, emp_id, delivery_date) values (31,7,'2016-08-12');
insert into schedule (id, emp_id, delivery_date) values (32,26,'2016-08-19');
insert into schedule (id, emp_id, delivery_date) values (33,1,'2016-08-26');
insert into schedule (id, emp_id, delivery_date) values (34,9,'2016-09-02');
insert into schedule (id, emp_id, delivery_date) values (35,16,'2016-09-09');
insert into schedule (id, emp_id, delivery_date) values (36,2,'2016-09-16');
insert into schedule (id, emp_id, delivery_date) values (37,17,'2016-09-23');
insert into schedule (id, emp_id, delivery_date) values (38,20,'2016-09-30');
insert into schedule (id, emp_id, delivery_date) values (39,10,'2016-10-07');
insert into schedule (id, emp_id, delivery_date) values (40,18,'2016-10-14');
insert into schedule (id, emp_id, delivery_date) values (41,25,'2016-10-21');  
insert into schedule (id, emp_id, delivery_date) values (42,6,'2016-10-28');
insert into schedule (id, emp_id, delivery_date) values (43,26,'2016-11-04');
insert into schedule (id, emp_id, delivery_date) values (44,21,'2016-11-11');
insert into schedule (id, emp_id, delivery_date) values (45,22,'2016-11-18');
insert into schedule (id, emp_id, delivery_date) values (46,19,'2016-11-25');
insert into schedule (id, emp_id, delivery_date) values (47,12,'2016-12-02');
insert into schedule (id, emp_id, delivery_date) values (48,27,'2016-12-09'); 
insert into schedule (id, emp_id, delivery_date) values (49,3,'2016-12-16');
insert into schedule (id, emp_id, delivery_date) values (50,15,'2016-12-23');
insert into schedule (id, emp_id, delivery_date) values (51,7,'2016-12-30');
